import { LineContainer } from '@features/wordle/components/LineContainer'
import { useLines } from '@features/wordle/lines.slice'
import { nextPosition, previousPosition } from '@features/wordle/position.slice'
import { Line } from '@features/wordle/types'
import { useAppDispatch } from '@redux/hooks'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const lines:Line[] = useLines()
  const dispatcher = useAppDispatch()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={`${styles.title} pb-4`}>Wordle 4 Kids</h1> */}
        <h1 className={`${styles.title} pb-4`}>----</h1>
        <div className='inline-flex mb-4'>
          <button className='bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-l'
                  onClick={()=>dispatcher(previousPosition())}
          >
            Prev
          </button>
          <button className='bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-r'
                  onClick={()=>dispatcher(nextPosition())}
          >
            Next
          </button>
        </div>
        <div className='grid grid-cols-5 grid-flow-row gap-4'>
          <LineContainer lines={lines}></LineContainer>
        </div>
      </main>
    </div>
  )
}

export default Home
