import { BoardContainer } from '@features/wordle/components/BoardContainer'
import { LineContainer } from '@features/wordle/components/LineContainer'
import { Box, Line } from '@features/wordle/types'
import produce from 'immer'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const baseBox: Box = {
    position: 1,
    letter: '',
    filled: false,
    fullMatch: false,
    match: false,
  }

  const baseLine: Line = {
    position: 1,
    boxes: [1,2,3.4,5].map((i) => ({ ...baseBox, position: i })),
  }

  const lines: Line[] = [1,2,3,4,5].map((i) =>
    produce(baseLine, (draftLine) => (void(draftLine.position = i)))
  )

  console.log(lines)

  // const lines = [
  //   [1, 2, 3, 4, 5],
  //   [1, 2, 3, 4, 5],
  //   [1, 2, 3, 4, 5],
  //   [1, 2, 3, 4, 5],
  //   [1, 2, 3, 4, 5],
  // ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={`${styles.title} pb-4`}>Wordle 4 Kids</h1>
        <div className='grid grid-cols-5 grid-flow-row gap-4'>
          <BoardContainer>
            <LineContainer lines={lines}></LineContainer>
          </BoardContainer>
        </div>
      </main>
    </div>
  )
}

export default Home
