import { NotificationTypes } from '@features/notifications/components/Notifications'
import { addNotification } from '@features/notifications/notification.slice'
import { useAppDispatch } from '@redux/hooks'
import type { NextPage } from 'next'

import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const dispatch = useAppDispatch()
  const notification: NotificationTypes = 'success'

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button
          onClick={() => {
            dispatch(
              addNotification({
                message: 'This is a notification',
                type: notification,
              })
            )
          }}
        >
          add Notification
        </button>
      </main>
    </div>
  )
}

export default Home
